name: Build for iOS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to build'
        required: false
        default: 'main'

jobs:
  build-ios:
    name: Release iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Update version in pubspec.yaml
        run: |
          version_name=$(yq e '.version' pubspec.yaml | cut -d "+" -f 1)
          build_number=$(git rev-list --count HEAD)
          sed -i '' "s/^version: .*/version: $version_name+$build_number/" pubspec.yaml

      - name: Build iOS (no codesign)
        run: |
          chmod +x lib/scripts/build.sh
          lib/scripts/build.sh
          flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          # remove any old Payload
          rm -rf Payload
          # create a real Payload directory
          mkdir Payload
          # copy the real app bundle
          cp -R build/ios/iphoneos/Runner.app Payload/
          # use ditto to create a proper .ipa (preserves metadata)
          ditto -c -k --sequesterRsrc --keepParent Payload ios-release-no-sign.ipa

      - name: Upload iOS release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: ios-release-no-sign.ipa
