name: Build for iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build & Package iOS (unsigned)
    runs-on: macos-latest

    # 国内镜像
    env:
      PUB_HOSTED_URL: https://pub.flutter-io.cn
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Pre-get flutter packages
        run: flutter pub get

      - name: Update version in pubspec.yaml
        run: |
          version_name=$(yq e '.version' pubspec.yaml | cut -d "+" -f 1)
          build_number=$(git rev-list --count HEAD)
          sed -i '' "s/^version: .*/version: $version_name+$build_number/" pubspec.yaml

      - name: Build & Package iOS (no codesign)
        run: |
          # 1. 编译出无签名 App
          chmod +x lib/scripts/build.sh
          lib/scripts/build.sh
          flutter build ios --release --no-codesign

          # 2. 打包成 Payload 目录
          rm -rf Payload
          mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/

          # 3. 用 ditto 生成 .ipa（保留元数据）
          ditto -c -k --sequesterRsrc --keepParent Payload ios-release-no-sign.ipa

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: ios-release-no-sign.ipa
